### ISSUE TITLE
Block touch events

### ISSUE THREAD

**Issue by MobileMon** [pingpongboss/StandOut#10]
Lets say I have a simple window on top of an activity's button. How can I press the button through the simple window?

**Comment by pingpongboss** [comment]
This is not supported out of the box, so you'll have to edit StandOutWindow.java. Check out the constructor StandOutLayoutParams(int id) and instead of using the flags StandOutLayoutParams.FLAG_NOT_TOUCH_MODAL | StandOutLayoutParams.FLAG_WATCH_OUTSIDE_TOUCH, use something like FLAG_NOT_FOCUSABLE or FLAG_NOT_TOUCHABLE http://developer.android.com/reference/android/view/WindowManager.LayoutParams.html

If you want to enable/disable this on-demand, use updateViewLayout()
